modLoader="javafml"
loaderVersion="[52,)"
license="MIT License"
[[mods]]
modId="harderfarthercore"
version="${file.jarVersion}"
displayName="Harder Farther Core"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-farther-core"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Farther Core.'
[[dependencies.harderfarthercore]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarthercore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"


