# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[55,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT"
[[mods]]
modId="harderfarthercore"
version="${file.jarVersion}"
displayName="Harder Farther Core"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-farther-core"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Farther Core.'
[[dependencies.harderfarthercore]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarthercore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"


